import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1789571478360 implements MigrationInterface {
    name = 'InitSchema1789571478360'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenant_id" uuid NOT NULL, "workspace_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "code" character varying(50) NOT NULL, "name" character varying(80) NOT NULL, "description" character varying(255), "permissions" jsonb NOT NULL DEFAULT '[]', "is_system" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e59a01f4fe46ebbece575d9a0f" ON "roles" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5291e7ee78e540217bd44bd368" ON "roles" ("workspace_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3742e5465d865991e445c46543" ON "roles" ("tenant_id", "code") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenant_id" uuid NOT NULL, "workspace_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "email" character varying(160) NOT NULL, "phone" character varying(32), "display_name" character varying(80) NOT NULL, "password_hash" character varying(120) NOT NULL, "avatar_url" character varying(512), "status" character varying(32) NOT NULL DEFAULT 'active', "is_super_admin" boolean NOT NULL DEFAULT false, "last_login_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_109638590074998bb72a2f2cf0" ON "users" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9ef32eab3ccaf4744fd36317c1" ON "users" ("workspace_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e9f4c2efab52114c4e99e28efb" ON "users" ("tenant_id", "email") `);
        await queryRunner.query(`CREATE TABLE "workspaces" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenant_id" uuid NOT NULL, "workspace_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying(100) NOT NULL, "slug" character varying(50) NOT NULL, "status" character varying(32) NOT NULL DEFAULT 'active', "settings" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "PK_098656ae401f3e1a4586f47fd8e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c740a9889952feb1c90a83fdb1" ON "workspaces" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5caa470396a1512cf146272e60" ON "workspaces" ("workspace_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b8e9fe62e93d60089dfc4f175f" ON "workspaces" ("slug") `);
        await queryRunner.query(`CREATE TABLE "contents" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenant_id" uuid NOT NULL, "workspace_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "title" character varying(200) NOT NULL, "summary" character varying(500), "body" text NOT NULL, "cover_url" character varying(512), "media_urls" jsonb NOT NULL DEFAULT '[]', "tags" jsonb NOT NULL DEFAULT '[]', "status" character varying(32) NOT NULL DEFAULT 'draft', "ai_generated" boolean NOT NULL DEFAULT false, "ai_flag_type" character varying(32) NOT NULL DEFAULT 'none', "ai_flag_checked" boolean NOT NULL DEFAULT false, "brand_knowledge_id" uuid, "author_id" uuid, "published_at" TIMESTAMP WITH TIME ZONE, "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_b7c504072e537532d7080c54fac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c49f0a05e08e37688248d0a3f3" ON "contents" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ba2881414ee0f256251aec42b6" ON "contents" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cefd396cc5fe069703218286d7" ON "contents" ("status") `);
        await queryRunner.query(`CREATE TABLE "content_variants" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenant_id" uuid NOT NULL, "workspace_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "content_id" uuid NOT NULL, "platform" character varying(40) NOT NULL, "title" character varying(200) NOT NULL, "body" text NOT NULL, "tags" jsonb NOT NULL DEFAULT '[]', "media_urls" jsonb NOT NULL DEFAULT '[]', "status" character varying(32) NOT NULL DEFAULT 'draft', "ai_generated" boolean NOT NULL DEFAULT false, "ai_flag_type" character varying(32) NOT NULL DEFAULT 'none', "generation_id" uuid, "extra" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "PK_6779d2ead0457826a89d07a596f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_845cb1b2665dcd31dbcaf1481b" ON "content_variants" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0d6a18b587b340dfd98182129b" ON "content_variants" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_53e08440965192fa244bcbd098" ON "content_variants" ("platform") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2184790287edf4bfe4809431b0" ON "content_variants" ("content_id", "platform") `);
        await queryRunner.query(`CREATE TABLE "platforms" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenant_id" uuid NOT NULL, "workspace_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "code" character varying(40) NOT NULL, "name" character varying(80) NOT NULL, "publish_mode" character varying(16) NOT NULL, "capabilities" jsonb NOT NULL DEFAULT '{}', "is_active" boolean NOT NULL DEFAULT true, "sort_order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_3b879853678f7368d46e52b81c6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_440a3af14795b16f407646ac7e" ON "platforms" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_752e036bfa90a02a16a294f22d" ON "platforms" ("workspace_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f2dfc2261c3cb3322162a3b061" ON "platforms" ("code") `);
        await queryRunner.query(`CREATE TABLE "social_accounts" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenant_id" uuid NOT NULL, "workspace_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "platform_id" uuid NOT NULL, "platform_code" character varying(40) NOT NULL, "account_name" character varying(120) NOT NULL, "platform_account_id" character varying(160) NOT NULL, "avatar_url" character varying(512), "access_token" character varying(1024), "refresh_token" character varying(1024), "token_expires_at" TIMESTAMP WITH TIME ZONE, "status" character varying(32) NOT NULL DEFAULT 'active', "bound_by" uuid, "last_synced_at" TIMESTAMP WITH TIME ZONE, "extra" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "PK_e9e58d2d8e9fafa20af914d9750" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2299331ad1b272f712c291ff74" ON "social_accounts" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1d56c066118eb434c228cb1075" ON "social_accounts" ("workspace_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e00ba892e09485cb57fe5f2b10" ON "social_accounts" ("workspace_id", "platform_id", "platform_account_id") `);
        await queryRunner.query(`CREATE TABLE "publish_tasks" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenant_id" uuid NOT NULL, "workspace_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "content_id" uuid NOT NULL, "content_variant_id" uuid, "platform" character varying(40) NOT NULL, "publish_mode" character varying(16) NOT NULL, "social_account_id" uuid, "status" character varying(32) NOT NULL DEFAULT 'pending', "scheduled_at" TIMESTAMP WITH TIME ZONE, "started_at" TIMESTAMP WITH TIME ZONE, "finished_at" TIMESTAMP WITH TIME ZONE, "attempts" integer NOT NULL DEFAULT '0', "max_attempts" integer NOT NULL DEFAULT '3', "error_message" text, "platform_post_id" character varying(160), "platform_url" character varying(512), "created_by" uuid, "locked_by" character varying(80), "locked_at" TIMESTAMP WITH TIME ZONE, "extra" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "PK_3bac32297d7696181502e7defa1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_77b8c2e1e492bccad77663a473" ON "publish_tasks" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9ddcd54fb949ca2a1ea1467b4b" ON "publish_tasks" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2ac3cdf306735bd646be23bfbb" ON "publish_tasks" ("content_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_51afe3304890be08f6b4f07f2b" ON "publish_tasks" ("platform") `);
        await queryRunner.query(`CREATE INDEX "IDX_ff37bc94d883789e535ea369f6" ON "publish_tasks" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_aca8f4bff7635051f3ab2dd9bc" ON "publish_tasks" ("status", "scheduled_at") `);
        // 注意：approvals 表已在迁移 1789700600000-DropApprovals 中删除（历史空壳表，代码从未引用）
        await queryRunner.query(`CREATE TABLE "approvals" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenant_id" uuid NOT NULL, "workspace_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "target_type" character varying(32) NOT NULL, "target_id" uuid NOT NULL, "status" character varying(32) NOT NULL DEFAULT 'pending', "requested_by" uuid, "reviewed_by" uuid, "comment" text, "reviewed_at" TIMESTAMP WITH TIME ZONE, "payload" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "PK_690417aaefa84d18b1a59e2a499" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_63e5eac9d0712aee7c49014a82" ON "approvals" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_98637628f162aa5d902ab38cca" ON "approvals" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_59c3bb845215eb6ceb5087e23a" ON "approvals" ("target_type", "target_id") `);
        await queryRunner.query(`CREATE TABLE "content_reviews" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenant_id" uuid NOT NULL, "workspace_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "content_id" uuid NOT NULL, "reviewer_id" uuid, "round" integer NOT NULL DEFAULT '1', "status" character varying(32) NOT NULL DEFAULT 'pending', "comments" text, "checklist" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "PK_5116678c7f41c2f4c4e02e2a128" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d6315b9c7fbd95b2b8b953a3d8" ON "content_reviews" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7615cf016324600908c689eb03" ON "content_reviews" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4a618430c2ef32e8e85456e111" ON "content_reviews" ("content_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_316d656ac45cd05aa19d2f5fd4" ON "content_reviews" ("status") `);
        await queryRunner.query(`CREATE TABLE "brand_knowledge" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenant_id" uuid NOT NULL, "workspace_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "brand" character varying(80) NOT NULL, "category" character varying(60) NOT NULL, "title" character varying(200) NOT NULL, "content" text NOT NULL, "tags" jsonb NOT NULL DEFAULT '[]', "source_url" character varying(512), "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_568bdc90ea24765191b43f2342d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9420d1fa1085e88bfc43fc8d18" ON "brand_knowledge" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_921a7fa01beb544b085412de80" ON "brand_knowledge" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b1ea716762036862e94c7b8b98" ON "brand_knowledge" ("brand") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenant_id" uuid NOT NULL, "workspace_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actor_id" uuid, "actor_name" character varying(80), "action" character varying(80) NOT NULL, "resource_type" character varying(60) NOT NULL, "resource_id" character varying(64), "ip" character varying(64), "user_agent" character varying(255), "payload" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6f18d459490bb48923b1f40bdb" ON "audit_logs" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e140f8ddef870ea93925f251f2" ON "audit_logs" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_3d04b6f2b05825501c1427f0d9" ON "audit_logs" ("resource_type", "resource_id") `);
        await queryRunner.query(`CREATE TABLE "track_events" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenant_id" uuid NOT NULL, "workspace_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "event_name" character varying(80) NOT NULL, "platform" character varying(40), "content_id" uuid, "content_variant_id" uuid, "social_account_id" uuid, "session_id" character varying(80), "occurred_at" TIMESTAMP WITH TIME ZONE NOT NULL, "properties" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "PK_3cd85a372b7560a9834c1f1df3e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_318a5fece2bde05b3680f2100d" ON "track_events" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_13fbd0a41f9d2501b31fdcc9f5" ON "track_events" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_044dade0857b8c2e5bfd261098" ON "track_events" ("event_name", "occurred_at") `);
        await queryRunner.query(`CREATE TABLE "analytics" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenant_id" uuid NOT NULL, "workspace_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "content_id" uuid, "content_variant_id" uuid, "publish_task_id" uuid, "platform" character varying(40) NOT NULL, "social_account_id" uuid, "platform_post_id" character varying(160), "captured_at" TIMESTAMP WITH TIME ZONE NOT NULL, "views" integer NOT NULL DEFAULT '0', "likes" integer NOT NULL DEFAULT '0', "comments" integer NOT NULL DEFAULT '0', "shares" integer NOT NULL DEFAULT '0', "favorites" integer NOT NULL DEFAULT '0', "followers" integer NOT NULL DEFAULT '0', "extra" jsonb NOT NULL DEFAULT '{}', CONSTRAINT "PK_3c96dcbf1e4c57ea9e0c3144bff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1ccf67e1c6b255edf3a1379145" ON "analytics" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_23cd438de7419be065d662c3d5" ON "analytics" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_14c7cf6ba4ddaaf2747559ff29" ON "analytics" ("platform") `);
        await queryRunner.query(`CREATE INDEX "IDX_0b43e5ab01ff28354c9a6ddc77" ON "analytics" ("content_id", "captured_at") `);
        await queryRunner.query(`CREATE TABLE "ai_generations" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenant_id" uuid NOT NULL, "workspace_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "provider" character varying(40) NOT NULL, "model" character varying(80) NOT NULL, "task_type" character varying(40) NOT NULL, "status" character varying(32) NOT NULL DEFAULT 'success', "prompt" text NOT NULL, "output" text, "input_refs" jsonb NOT NULL DEFAULT '{}', "tokens_input" integer NOT NULL DEFAULT '0', "tokens_output" integer NOT NULL DEFAULT '0', "latency_ms" integer NOT NULL DEFAULT '0', "cost" numeric(12,6) NOT NULL DEFAULT '0', "error_message" text, "requested_by" uuid, "content_id" uuid, "content_variant_id" uuid, CONSTRAINT "PK_ac39086528be836b5aac57d3896" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fa42646d340dc50f0227752235" ON "ai_generations" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1961f132b8336ebe3c790b9769" ON "ai_generations" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9f66fcd5c06a8c219d716152b0" ON "ai_generations" ("task_type") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("users_id" uuid NOT NULL, "roles_id" uuid NOT NULL, CONSTRAINT "PK_65ec3daed53f391c53df7e2e8fb" PRIMARY KEY ("users_id", "roles_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8e1215206acb19f1c38dbda909" ON "user_roles" ("users_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4a08d003e00caf075a4a212d23" ON "user_roles" ("roles_id") `);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_9ef32eab3ccaf4744fd36317c15" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contents" ADD CONSTRAINT "FK_ef9aa2f7890c5652724605b6724" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "content_variants" ADD CONSTRAINT "FK_4af9505a1ef66403b4172d7e170" FOREIGN KEY ("content_id") REFERENCES "contents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "social_accounts" ADD CONSTRAINT "FK_c96d616e8999ea2d23ff259e75e" FOREIGN KEY ("platform_id") REFERENCES "platforms"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "publish_tasks" ADD CONSTRAINT "FK_2ac3cdf306735bd646be23bfbba" FOREIGN KEY ("content_id") REFERENCES "contents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "publish_tasks" ADD CONSTRAINT "FK_849b976af0ffc8bd2d5f125430f" FOREIGN KEY ("content_variant_id") REFERENCES "content_variants"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "publish_tasks" ADD CONSTRAINT "FK_4878d57d2d61ae3ead1f75fc231" FOREIGN KEY ("social_account_id") REFERENCES "social_accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "content_reviews" ADD CONSTRAINT "FK_4a618430c2ef32e8e85456e1111" FOREIGN KEY ("content_id") REFERENCES "contents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "analytics" ADD CONSTRAINT "FK_de273f971225163b108b04d100f" FOREIGN KEY ("content_id") REFERENCES "contents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_8e1215206acb19f1c38dbda9091" FOREIGN KEY ("users_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_4a08d003e00caf075a4a212d23d" FOREIGN KEY ("roles_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_4a08d003e00caf075a4a212d23d"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_8e1215206acb19f1c38dbda9091"`);
        await queryRunner.query(`ALTER TABLE "analytics" DROP CONSTRAINT "FK_de273f971225163b108b04d100f"`);
        await queryRunner.query(`ALTER TABLE "content_reviews" DROP CONSTRAINT "FK_4a618430c2ef32e8e85456e1111"`);
        await queryRunner.query(`ALTER TABLE "publish_tasks" DROP CONSTRAINT "FK_4878d57d2d61ae3ead1f75fc231"`);
        await queryRunner.query(`ALTER TABLE "publish_tasks" DROP CONSTRAINT "FK_849b976af0ffc8bd2d5f125430f"`);
        await queryRunner.query(`ALTER TABLE "publish_tasks" DROP CONSTRAINT "FK_2ac3cdf306735bd646be23bfbba"`);
        await queryRunner.query(`ALTER TABLE "social_accounts" DROP CONSTRAINT "FK_c96d616e8999ea2d23ff259e75e"`);
        await queryRunner.query(`ALTER TABLE "content_variants" DROP CONSTRAINT "FK_4af9505a1ef66403b4172d7e170"`);
        await queryRunner.query(`ALTER TABLE "contents" DROP CONSTRAINT "FK_ef9aa2f7890c5652724605b6724"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_9ef32eab3ccaf4744fd36317c15"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a08d003e00caf075a4a212d23"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e1215206acb19f1c38dbda909"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f66fcd5c06a8c219d716152b0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1961f132b8336ebe3c790b9769"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fa42646d340dc50f0227752235"`);
        await queryRunner.query(`DROP TABLE "ai_generations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0b43e5ab01ff28354c9a6ddc77"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_14c7cf6ba4ddaaf2747559ff29"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_23cd438de7419be065d662c3d5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ccf67e1c6b255edf3a1379145"`);
        await queryRunner.query(`DROP TABLE "analytics"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_044dade0857b8c2e5bfd261098"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13fbd0a41f9d2501b31fdcc9f5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_318a5fece2bde05b3680f2100d"`);
        await queryRunner.query(`DROP TABLE "track_events"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d04b6f2b05825501c1427f0d9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e140f8ddef870ea93925f251f2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6f18d459490bb48923b1f40bdb"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b1ea716762036862e94c7b8b98"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_921a7fa01beb544b085412de80"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9420d1fa1085e88bfc43fc8d18"`);
        await queryRunner.query(`DROP TABLE "brand_knowledge"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_316d656ac45cd05aa19d2f5fd4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a618430c2ef32e8e85456e111"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7615cf016324600908c689eb03"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d6315b9c7fbd95b2b8b953a3d8"`);
        await queryRunner.query(`DROP TABLE "content_reviews"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_59c3bb845215eb6ceb5087e23a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_98637628f162aa5d902ab38cca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_63e5eac9d0712aee7c49014a82"`);
        await queryRunner.query(`DROP TABLE "approvals"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aca8f4bff7635051f3ab2dd9bc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff37bc94d883789e535ea369f6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_51afe3304890be08f6b4f07f2b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2ac3cdf306735bd646be23bfbb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9ddcd54fb949ca2a1ea1467b4b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77b8c2e1e492bccad77663a473"`);
        await queryRunner.query(`DROP TABLE "publish_tasks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e00ba892e09485cb57fe5f2b10"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1d56c066118eb434c228cb1075"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2299331ad1b272f712c291ff74"`);
        await queryRunner.query(`DROP TABLE "social_accounts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f2dfc2261c3cb3322162a3b061"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_752e036bfa90a02a16a294f22d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_440a3af14795b16f407646ac7e"`);
        await queryRunner.query(`DROP TABLE "platforms"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2184790287edf4bfe4809431b0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_53e08440965192fa244bcbd098"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0d6a18b587b340dfd98182129b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_845cb1b2665dcd31dbcaf1481b"`);
        await queryRunner.query(`DROP TABLE "content_variants"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cefd396cc5fe069703218286d7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba2881414ee0f256251aec42b6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c49f0a05e08e37688248d0a3f3"`);
        await queryRunner.query(`DROP TABLE "contents"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b8e9fe62e93d60089dfc4f175f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5caa470396a1512cf146272e60"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c740a9889952feb1c90a83fdb1"`);
        await queryRunner.query(`DROP TABLE "workspaces"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9f4c2efab52114c4e99e28efb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9ef32eab3ccaf4744fd36317c1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_109638590074998bb72a2f2cf0"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3742e5465d865991e445c46543"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5291e7ee78e540217bd44bd368"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e59a01f4fe46ebbece575d9a0f"`);
        await queryRunner.query(`DROP TABLE "roles"`);
    }

}
