#!/usr/bin/env node
// Emits dist/tokens.css and dist/tokens.json from the single source of truth (src/tokens.json).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, '..');
const distDir = resolve(pkgRoot, 'dist');

const tokens = JSON.parse(readFileSync(resolve(pkgRoot, 'src/tokens.json'), 'utf8'));
const PREFIX = '--mf';

function flatten(node, path, out) {
  for (const [key, value] of Object.entries(node)) {
    const next = [...path, key];
    if (value && typeof value === 'object') flatten(value, next, out);
    else out.push([next.join('-'), value]);
  }
  return out;
}

const pairs = flatten(tokens, [], []);
const lines = pairs.map(([name, value]) => `  ${PREFIX}-${name}: ${value};`);
const css = `/* Generated by scripts/build.mjs - do not edit by hand. */\n:root {\n${lines.join('\n')}\n}\n`;

mkdirSync(distDir, { recursive: true });
writeFileSync(resolve(distDir, 'tokens.css'), css, 'utf8');
writeFileSync(resolve(distDir, 'tokens.json'), JSON.stringify(tokens, null, 2), 'utf8');
process.stdout.write(`design-tokens: wrote ${pairs.length} css variables\n`);
