export type SettingGroup = 'site' | 'permissions' | 'ai' | 'compliance' | 'knowledge' | 'publish' | 'platform';

export interface SettingDefinition {
  key: string;
  group: SettingGroup;
  label: string;
  description: string;
  secret: boolean;
  /** Environment variable used as the fallback when nothing is stored in the database. */
  envKey: string;
  placeholder?: string;
  options?: Array<{ value: string; label: string }>;
}

/**
 * Every configurable key lives here. The database wins over the environment, so an operator
 * can configure the system from the UI while a fresh clone still works from .env only.
 */
export const SETTING_DEFINITIONS: SettingDefinition[] = [
  {
    key: 'AI_PROVIDER',
    group: 'ai',
    label: 'AI 提供方',
    description: 'mock = 离线模板（不消耗额度），deepseek = 真实调用',
    secret: false,
    envKey: 'AI_PROVIDER',
    options: [
      { value: 'deepseek', label: 'DeepSeek（真实调用）' },
      { value: 'mock', label: '离线模板（不调用外部接口）' },
    ],
  },
  {
    key: 'AI_MODEL',
    group: 'ai',
    label: '模型名称',
    description: 'DeepSeek 模型标识别，例如 deepseek-v4-flash-0731',
    secret: false,
    envKey: 'AI_MODEL',
    placeholder: 'deepseek-v4-flash-0731',
  },
  {
    key: 'AI_API_KEY',
    group: 'ai',
    label: 'AI API Key',
    description: 'DeepSeek 密钥；加密存储在数据库中，界面上只显示后四位',
    secret: true,
    envKey: 'AI_API_KEY',
    placeholder: 'sk-...',
  },
  {
    key: 'AI_API_BASE',
    group: 'ai',
    label: 'AI 接口地址',
    description: '留空使用官方地址 https://api.deepseek.com',
    secret: false,
    envKey: 'AI_API_BASE',
    placeholder: 'https://api.deepseek.com',
  },
  {
    key: 'SITE_NAME',
    group: 'site',
    label: '站点名称',
    description: '侧边栏、登录页、浏览器标题、浏览器插件弹窗都用它；交给别的公司时改这里',
    secret: false,
    envKey: 'SITE_NAME',
    placeholder: 'MediaFlow',
  },
  {
    key: 'SITE_TAGLINE',
    group: 'site',
    label: '站点副标题',
    description: '侧边栏与登录页的一行说明',
    secret: false,
    envKey: 'SITE_TAGLINE',
    placeholder: '内容分发与矩阵运营',
  },
  {
    key: 'COMPANY_NAME',
    group: 'site',
    label: '公司名称',
    description: '用于页脚与导出文件署名，可留空',
    secret: false,
    envKey: 'COMPANY_NAME',
  },
  {
    key: 'SUPPORT_EMAIL',
    group: 'site',
    label: '支持邮箱',
    description: '显示在登录页与帮助说明里，可留空',
    secret: false,
    envKey: 'SUPPORT_EMAIL',
  },
  {
    key: 'UI_PAGE_SIZE',
    group: 'site',
    label: '列表每页条数',
    description: '默认 10，可按团队习惯调整（5-100）',
    secret: false,
    envKey: 'UI_PAGE_SIZE',
    placeholder: '10',
  },
  {
    key: 'SITE_BRAND_COLOR',
    group: 'site',
    label: '品牌主色（十六进制）',
    description: '界面按钮、链接、标签的主色；填一个颜色，系统自动推导深浅色阶（例如 #4F6BFF）',
    secret: false,
    envKey: 'SITE_BRAND_COLOR',
    placeholder: '#4F6BFF',
  },
  {
    key: 'SITE_LOGO_URL',
    group: 'site',
    label: 'Logo 图片地址',
    description: '侧边栏左上角使用；留空则用站点名首字作为图标',
    secret: false,
    envKey: 'SITE_LOGO_URL',
    placeholder: 'https://example.com/logo.png',
  },
  {
    key: 'AI_DISCLOSURE_SUFFIX',
    group: 'site',
    label: 'AI 生成内容标识后缀',
    description: 'AI 生成内容发布时自动追加的显式标识（法定要求，可改文案）',
    secret: false,
    envKey: 'AI_DISCLOSURE_SUFFIX',
    placeholder: '（本文由 AI 辅助生成）',
  },
  {
    key: 'PERMISSION_MATRIX',
    group: 'permissions',
    label: '权限矩阵（JSON）',
    description:
      '能力点 → 允许的角色。可用能力点：settings.write（改设置）、users.manage（管用户）、users.privileged（删用户/改角色）、content.write（写内容）、content.review（审核）、publish.execute（发布）、knowledge.write（知识库）、platform.bind（绑账号）、analytics.sync（同步数据）',
    secret: false,
    envKey: 'PERMISSION_MATRIX',
    placeholder: '{"settings.write":["owner","admin"],"publish.execute":["owner","admin","editor"]}',
  },
  {
    key: 'AUTH_ACCESS_EXPIRES',
    group: 'permissions',
    label: '登录有效期',
    description: '访问令牌有效期，默认 2h；到期前端会自动用刷新令牌续期',
    secret: false,
    envKey: 'JWT_ACCESS_EXPIRES',
    placeholder: '2h',
  },
  {
    key: 'AUTH_REFRESH_EXPIRES',
    group: 'permissions',
    label: '免登录时长',
    description: '刷新令牌有效期，默认 7d；在这段时间内打开系统无需重新登录',
    secret: false,
    envKey: 'JWT_REFRESH_EXPIRES',
    placeholder: '7d',
  },
  {
    key: 'ROLE_LABELS',
    group: 'permissions',
    label: '角色显示名（JSON）',
    description: '把内置角色改成贵公司的叫法，例如 {"admin":"运营主管","reviewer":"内容负责人"}',
    secret: false,
    envKey: 'ROLE_LABELS',
    placeholder: '{"admin":"运营主管"}',
  },
  {
    key: 'AI_SYSTEM_PROMPT',
    group: 'ai',
    label: 'AI 写作规范（系统提示词）',
    description: '全局写作基调与合规要求；换行业主要改这里',
    secret: false,
    envKey: 'AI_SYSTEM_PROMPT',
  },
  {
    key: 'AI_PLATFORM_GUIDANCE',
    group: 'ai',
    label: '各平台风格指引（JSON）',
    description: 'key 为平台代码，value 为该平台的写作要求',
    secret: false,
    envKey: 'AI_PLATFORM_GUIDANCE',
    placeholder: '{"xiaohongshu":"种草笔记，第一人称，300 字以内"}',
  },
  {
    key: 'AI_TEMPERATURE',
    group: 'ai',
    label: '生成随机度（temperature）',
    description: '0-2，越大越发散；合规要求高的场景建议 0.3-0.7',
    secret: false,
    envKey: 'AI_TEMPERATURE',
    placeholder: '0.7',
  },
  {
    key: 'AI_MAX_TOKENS',
    group: 'ai',
    label: '最大输出长度（token）',
    description: '推理模型的思考过程也占这个额度，给少了会只有思考没有正文',
    secret: false,
    envKey: 'AI_MAX_TOKENS',
    placeholder: '4096',
  },
  {
    key: 'AI_PRICE_INPUT_PER_MTOK',
    group: 'ai',
    label: '输入价格（元/百万 token）',
    description: '用于统计 AI 花费；按服务商当前价格填写，填 0 表示不计成本',
    secret: false,
    envKey: 'AI_PRICE_INPUT_PER_MTOK',
    placeholder: '2',
  },
  {
    key: 'AI_PRICE_OUTPUT_PER_MTOK',
    group: 'ai',
    label: '输出价格（元/百万 token）',
    description: '用于统计 AI 花费；推理模型的思考 token 也算输出',
    secret: false,
    envKey: 'AI_PRICE_OUTPUT_PER_MTOK',
    placeholder: '8',
  },
  {
    key: 'AI_RATE_LIMIT_PER_MINUTE',
    group: 'ai',
    label: '每分钟最多生成次数',
    description: '防止误触发把额度刷掉；填 0 表示不限制',
    secret: false,
    envKey: 'AI_RATE_LIMIT_PER_MINUTE',
    placeholder: '0',
  },
  {
    key: 'AI_DAILY_TOKEN_QUOTA',
    group: 'ai',
    label: '每日 token 上限',
    description: '当天累计 token 达到上限后停止调用，避免账单失控；填 0 表示不限制',
    secret: false,
    envKey: 'AI_DAILY_TOKEN_QUOTA',
    placeholder: '0',
  },
  {
    key: 'COMPLIANCE_RULES',
    group: 'compliance',
    label: '合规词库（JSON）',
    description: '违规词、原因与修改建议；换行业/换品类时按自己的红线改一遍即可',
    secret: false,
    envKey: 'COMPLIANCE_RULES',
  },
  {
    key: 'KB_INJECT_LIMIT',
    group: 'knowledge',
    label: 'AI 每次引用的资料条数',
    description: '默认 5 条，太多会稀释重点并推高 token 消耗',
    secret: false,
    envKey: 'KB_INJECT_LIMIT',
    placeholder: '5',
  },
  {
    key: 'KB_CHUNK_SIZE',
    group: 'knowledge',
    label: '文档切片长度（字）',
    description: '默认 1200',
    secret: false,
    envKey: 'KB_CHUNK_SIZE',
    placeholder: '1200',
  },
  {
    key: 'KB_CHUNK_OVERLAP',
    group: 'knowledge',
    label: '切片重叠长度（字）',
    description: '默认 200，避免语义被切断',
    secret: false,
    envKey: 'KB_CHUNK_OVERLAP',
    placeholder: '200',
  },
  {
    key: 'KB_MAX_CHUNKS',
    group: 'knowledge',
    label: '单份文档最多切片数',
    description: '默认 40，防止一份大文档灌爆知识库',
    secret: false,
    envKey: 'KB_MAX_CHUNKS',
    placeholder: '40',
  },
  {
    key: 'KB_MAX_DOCUMENT_MB',
    group: 'knowledge',
    label: '单文件大小上限（MB）',
    description: '默认 10',
    secret: false,
    envKey: 'KB_MAX_DOCUMENT_MB',
    placeholder: '10',
  },
  {
    key: 'KB_OCR_ENABLED',
    group: 'knowledge',
    label: '启用本地图片文字识别（OCR）',
    description: '离线 tesseract，不调用任何 AI 接口',
    secret: false,
    envKey: 'KB_OCR_ENABLED',
    options: [
      { value: 'true', label: '启用' },
      { value: 'false', label: '停用' },
    ],
  },
  {
    key: 'KB_OCR_LANGUAGES',
    group: 'knowledge',
    label: 'OCR 语言包',
    description: 'tesseract 语言代码，默认 chi_sim+eng',
    secret: false,
    envKey: 'KB_OCR_LANGUAGES',
    placeholder: 'chi_sim+eng',
  },
  {
    key: 'KB_OCR_MAX_IMAGES',
    group: 'knowledge',
    label: '单文档最多识别图片数',
    description: '默认 20',
    secret: false,
    envKey: 'KB_OCR_MAX_IMAGES',
    placeholder: '20',
  },
  {
    key: 'KB_OCR_PDF_MAX_PAGES',
    group: 'knowledge',
    label: '扫描版 PDF 最多识别页数',
    description: '默认 10',
    secret: false,
    envKey: 'KB_OCR_PDF_MAX_PAGES',
    placeholder: '10',
  },
  {
    key: 'KB_OCR_DPI',
    group: 'knowledge',
    label: 'PDF 渲染精度（DPI）',
    description: '默认 200，越大越准但越慢',
    secret: false,
    envKey: 'KB_OCR_DPI',
    placeholder: '200',
  },
  {
    key: 'NOTIFICATION_RETENTION_DAYS',
    group: 'publish',
    label: '通知保留天数',
    description: '超过该天数的站内通知会被自动清理（默认 90，填 0 表示永久保留）',
    secret: false,
    envKey: 'NOTIFICATION_RETENTION_DAYS',
    placeholder: '90',
  },
  {
    key: 'AI_METADATA_ENABLED',
    group: 'publish',
    label: '发布时写入 AI 生成标识元数据',
    description: '按《人工智能生成合成内容标识办法》要求，AI 生成内容的图片/视频需要隐式标识；开启后发布负载会带上元数据',
    secret: false,
    envKey: 'AI_METADATA_ENABLED',
    options: [
      { value: 'true', label: '开启' },
      { value: 'false', label: '关闭' },
    ],
  },
  {
    key: 'PUBLISH_STREAM_NAME',
    group: 'publish',
    label: '队列名称',
    description: 'Redis Stream 名称，默认 mediaflow:publish:tasks；改名前请确认没有排队中的任务',
    secret: false,
    envKey: 'PUBLISH_STREAM_NAME',
    placeholder: 'mediaflow:publish:tasks',
  },
  {
    key: 'PUBLISH_GROUP_NAME',
    group: 'publish',
    label: '消费组名称',
    description: '默认 publish-workers；与队列名一起改可让新环境使用独立队列',
    secret: false,
    envKey: 'PUBLISH_GROUP_NAME',
    placeholder: 'publish-workers',
  },
  {
    key: 'PUBLISH_MAX_ATTEMPTS',
    group: 'publish',
    label: '失败最多重试次数',
    description: '默认 3',
    secret: false,
    envKey: 'PUBLISH_MAX_ATTEMPTS',
    placeholder: '3',
  },
  {
    key: 'PUBLISH_READ_BLOCK_MS',
    group: 'publish',
    label: '队列空闲轮询间隔（毫秒）',
    description: '默认 5000',
    secret: false,
    envKey: 'PUBLISH_READ_BLOCK_MS',
    placeholder: '5000',
  },
  {
    key: 'PUBLISH_READ_COUNT',
    group: 'publish',
    label: '每次领取任务数',
    description: '默认 5',
    secret: false,
    envKey: 'PUBLISH_READ_COUNT',
    placeholder: '5',
  },
  {
    key: 'PUBLISH_CLAIM_IDLE_MS',
    group: 'publish',
    label: '卡住任务回收阈值（毫秒）',
    description: '默认 60000，worker 中途挂掉后超过这个时间会被重新领取',
    secret: false,
    envKey: 'PUBLISH_CLAIM_IDLE_MS',
    placeholder: '60000',
  },
  {
    key: 'KB_CATEGORIES',
    group: 'knowledge',
    label: '知识库分类配置',
    description: 'JSON 数组。平时不用手改——在「知识库管理 → 分类设置」里增删改即可，这里显示当前值，也方便整包配置导入导出',
    secret: false,
    envKey: 'KB_CATEGORIES',
    placeholder: '[{"code":"product","label":"产品卖点","tone":"success","description":"配方、规格、工艺"}]',
  },
  {
    key: 'WECHAT_MP_APP_ID',
    group: 'platform',
    label: '公众号 AppID',
    description: '用于拉取图文分析数据；公众号禁止 API 发布，仅供人工发布',
    secret: false,
    envKey: 'WECHAT_MP_APP_ID',
  },
  {
    key: 'WECHAT_MP_APP_SECRET',
    group: 'platform',
    label: '公众号 AppSecret',
    description: '加密存储',
    secret: true,
    envKey: 'WECHAT_MP_APP_SECRET',
  },
  {
    key: 'DOUYIN_CLIENT_KEY',
    group: 'platform',
    label: '抖音 Client Key',
    description: '发布接口需要 OAuth 授权；互动接口不可用',
    secret: false,
    envKey: 'DOUYIN_CLIENT_KEY',
  },
  {
    key: 'DOUYIN_CLIENT_SECRET',
    group: 'platform',
    label: '抖音 Client Secret',
    description: '加密存储',
    secret: true,
    envKey: 'DOUYIN_CLIENT_SECRET',
  },
  {
    key: 'XIAOHONGSHU_APP_ID',
    group: 'platform',
    label: '小红书 App ID',
    description: '需企业资质认证',
    secret: false,
    envKey: 'XIAOHONGSHU_APP_ID',
  },
  {
    key: 'XIAOHONGSHU_APP_SECRET',
    group: 'platform',
    label: '小红书 App Secret',
    description: '加密存储',
    secret: true,
    envKey: 'XIAOHONGSHU_APP_SECRET',
  },
  {
    key: 'XIAOHONGSHU_API_BASE',
    group: 'platform',
    label: '小红书开放平台地址',
    description: '留空时适配器不发起请求，只返回明确报错',
    secret: false,
    envKey: 'XIAOHONGSHU_API_BASE',
  },
  {
    key: 'REQUIRE_CONTENT_APPROVAL',
    group: 'publish',
    label: '发布前必须审核通过',
    description: '开启后，只有审核状态为「已通过」的内容才能创建发布任务',
    secret: false,
    envKey: 'REQUIRE_CONTENT_APPROVAL',
    options: [
      { value: 'true', label: '开启（推荐多人协作）' },
      { value: 'false', label: '关闭（小团队直接发布）' },
    ],
  },
  {
    key: 'PUBLISH_WORKER_ENABLED',
    group: 'publish',
    label: '启用发布 Worker',
    description: '关闭后任务只入队不执行（修改后需重启 API 生效）',
    secret: false,
    envKey: 'PUBLISH_WORKER_ENABLED',
    options: [
      { value: 'true', label: '启用' },
      { value: 'false', label: '停用' },
    ],
  },
  {
    key: 'PUBLISH_RETRY_INTERVAL_MS',
    group: 'publish',
    label: '失败重试间隔（毫秒）',
    description: '默认 300000（5 分钟）',
    secret: false,
    envKey: 'PUBLISH_RETRY_INTERVAL_MS',
    placeholder: '300000',
  },
];

export const SETTING_BY_KEY = new Map(SETTING_DEFINITIONS.map((definition) => [definition.key, definition]));

export const SETTING_GROUP_LABELS: Record<SettingGroup, string> = {
  site: '站点信息',
  permissions: '角色与权限',
  ai: 'AI 服务',
  compliance: '合规词库',
  knowledge: '知识库',
  publish: '发布队列',
  platform: '平台密钥',
};
