export type SettingGroup =
  | 'site'
  | 'permissions'
  | 'media'
  | 'ai'
  | 'compliance'
  | 'knowledge'
  | 'publish'
  | 'notify'
  | 'platform'
  | 'monitor'
  | 'workspace';

export interface SettingDefinition {
  key: string;
  group: SettingGroup;
  label: string;
  description: string;
  secret: boolean;
  /** Environment variable used as the fallback when nothing is stored in the database. */
  envKey: string;
  placeholder?: string;
  options?: Array<{ value: string; label: string }>;
}

/**
 * Every configurable key lives here. The database wins over the environment, so an operator
 * can configure the system from the UI while a fresh clone still works from .env only.
 */
export const SETTING_DEFINITIONS: SettingDefinition[] = [
  {
    key: 'AI_PROVIDER',
    group: 'ai',
    label: 'AI 提供方',
    description: 'mock = 离线模板（不消耗额度），deepseek = 真实调用',
    secret: false,
    envKey: 'AI_PROVIDER',
    options: [
      { value: 'deepseek', label: 'DeepSeek（真实调用）' },
      { value: 'mock', label: '离线模板（不调用外部接口）' },
    ],
  },
  {
    key: 'AI_MODEL',
    group: 'ai',
    label: '模型名称',
    description: 'DeepSeek 模型标识别，例如 deepseek-v4-flash-0731',
    secret: false,
    envKey: 'AI_MODEL',
    placeholder: 'deepseek-v4-flash-0731',
  },
  {
    key: 'AI_API_KEY',
    group: 'ai',
    label: 'AI API Key',
    description: 'DeepSeek 密钥；加密存储在数据库中，界面上只显示后四位',
    secret: true,
    envKey: 'AI_API_KEY',
    placeholder: 'sk-...',
  },
  {
    key: 'AI_API_BASE',
    group: 'ai',
    label: 'AI 接口地址',
    description: '留空使用官方地址 https://api.deepseek.com',
    secret: false,
    envKey: 'AI_API_BASE',
    placeholder: 'https://api.deepseek.com',
  },
  {
    key: 'SITE_NAME',
    group: 'site',
    label: '站点名称',
    description: '侧边栏、登录页、浏览器标题、浏览器插件弹窗都用它；交给别的公司时改这里',
    secret: false,
    envKey: 'SITE_NAME',
    placeholder: 'MediaFlow',
  },
  {
    key: 'SITE_TAGLINE',
    group: 'site',
    label: '站点副标题',
    description: '侧边栏与登录页的一行说明',
    secret: false,
    envKey: 'SITE_TAGLINE',
    placeholder: '内容分发与矩阵运营',
  },
  {
    key: 'COMPANY_NAME',
    group: 'site',
    label: '公司名称',
    description: '用于页脚与导出文件署名，可留空',
    secret: false,
    envKey: 'COMPANY_NAME',
  },
  {
    key: 'SUPPORT_EMAIL',
    group: 'site',
    label: '支持邮箱',
    description: '显示在登录页与帮助说明里，可留空',
    secret: false,
    envKey: 'SUPPORT_EMAIL',
  },
  {
    key: 'UI_PAGE_SIZE',
    group: 'site',
    label: '列表每页条数',
    description: '默认 10，可按团队习惯调整（5-100）',
    secret: false,
    envKey: 'UI_PAGE_SIZE',
    placeholder: '10',
  },
  {
    key: 'SITE_BRAND_COLOR',
    group: 'site',
    label: '品牌主色（十六进制）',
    description: '界面按钮、链接、标签的主色；填一个颜色，系统自动推导深浅色阶（例如 #4F6BFF）',
    secret: false,
    envKey: 'SITE_BRAND_COLOR',
    placeholder: '#4F6BFF',
  },
  {
    key: 'SITE_LOGO_URL',
    group: 'site',
    label: 'Logo 图片地址',
    description: '侧边栏左上角使用；留空则用站点名首字作为图标',
    secret: false,
    envKey: 'SITE_LOGO_URL',
    placeholder: 'https://example.com/logo.png',
  },
  {
    key: 'AI_DISCLOSURE_SUFFIX',
    group: 'site',
    label: 'AI 生成内容标识后缀',
    description: 'AI 生成内容发布时自动追加的显式标识（法定要求，可改文案）',
    secret: false,
    envKey: 'AI_DISCLOSURE_SUFFIX',
    placeholder: '（本文由 AI 辅助生成）',
  },
  {
    key: 'PERMISSION_MATRIX',
    group: 'permissions',
    label: '权限矩阵（JSON）',
    description:
      '能力点 → 允许的角色。可用能力点：settings.write（改设置）、users.manage（管用户）、users.privileged（删用户/改角色）、content.write（写内容）、content.review（审核）、publish.execute（发布）、knowledge.write（知识库）、platform.bind（绑账号）、analytics.sync（同步数据）、audit.read（看审计日志）、workspace.manage（管工作区）',
    secret: false,
    envKey: 'PERMISSION_MATRIX',
    placeholder: '{"settings.write":["owner","admin"],"publish.execute":["owner","admin","editor"]}',
  },
  {
    key: 'AUTH_ACCESS_EXPIRES',
    group: 'permissions',
    label: '登录有效期',
    description: '访问令牌有效期，默认 2h；到期前端会自动用刷新令牌续期',
    secret: false,
    envKey: 'JWT_ACCESS_EXPIRES',
    placeholder: '2h',
  },
  {
    key: 'AUTH_REFRESH_EXPIRES',
    group: 'permissions',
    label: '免登录时长',
    description: '刷新令牌有效期，默认 7d；在这段时间内打开系统无需重新登录',
    secret: false,
    envKey: 'JWT_REFRESH_EXPIRES',
    placeholder: '7d',
  },
  {
    key: 'AUTH_FORCE_PASSWORD_CHANGE',
    group: 'permissions',
    label: '临时密码强制改密',
    description:
      '开启后（默认）：管理员重置密码或邀请生成的临时密码，必须先改密才能使用其它功能，服务端强制；关闭则只在界面上提示',
    secret: false,
    envKey: 'AUTH_FORCE_PASSWORD_CHANGE',
    placeholder: 'true',
    options: [
      { value: 'true', label: '强制（推荐）' },
      { value: 'false', label: '仅提示' },
    ],
  },
  {
    key: 'ROLE_LABELS',
    group: 'permissions',
    label: '角色显示名（JSON）',
    description: '把内置角色改成贵公司的叫法，例如 {"admin":"运营主管","reviewer":"内容负责人"}',
    secret: false,
    envKey: 'ROLE_LABELS',
    placeholder: '{"admin":"运营主管"}',
  },
  {
    key: 'CONTENT_HISTORY_LIMIT',
    group: 'media',
    label: '内容版本历史保留条数',
    description: '每次保存前自动留一份上一版，改错可回滚；默认 20，填 0 表示不留历史',
    secret: false,
    envKey: 'CONTENT_HISTORY_LIMIT',
    placeholder: '20',
  },
  {
    key: 'NOTIFY_MIN_LEVEL',
    group: 'notify',
    label: '推送到群/邮件的最低级别',
    description: '默认只推 warning 与 error；选 info 会把所有站内通知都推出去（较吵）',
    secret: false,
    envKey: 'NOTIFY_MIN_LEVEL',
    options: [
      { value: 'warning', label: '警告及以上（推荐）' },
      { value: 'info', label: '全部（含普通提示）' },
      { value: 'error', label: '仅错误' },
    ],
  },
  {
    key: 'NOTIFY_WEBHOOK_URL',
    group: 'notify',
    label: '群机器人 Webhook 地址',
    description: '钉钉/飞书/企业微信机器人都可以；发布失败、账号掉线时推送到群里，留空则不推送',
    secret: false,
    envKey: 'NOTIFY_WEBHOOK_URL',
    placeholder: 'https://oapi.dingtalk.com/robot/send?access_token=...',
  },
  {
    key: 'NOTIFY_WEBHOOK_TYPE',
    group: 'notify',
    label: 'Webhook 类型',
    description: '按类型组装消息体，默认自动识别（钉钉/飞书/企业微信/通用 JSON）',
    secret: false,
    envKey: 'NOTIFY_WEBHOOK_TYPE',
    options: [
      { value: 'auto', label: '自动识别（按域名）' },
      { value: 'dingtalk', label: '钉钉机器人' },
      { value: 'feishu', label: '飞书机器人' },
      { value: 'wecom', label: '企业微信群机器人' },
      { value: 'generic', label: '通用 JSON（POST {title,text}）' },
    ],
  },
  {
    key: 'NOTIFY_EMAIL_ENABLED',
    group: 'notify',
    label: '启用邮件通知',
    description: '开启后发布失败与账号掉线会发邮件；需要下面的 SMTP 配置',
    secret: false,
    envKey: 'NOTIFY_EMAIL_ENABLED',
    options: [
      { value: 'false', label: '关闭' },
      { value: 'true', label: '开启' },
    ],
  },
  {
    key: 'NOTIFY_EMAIL_TO',
    group: 'notify',
    label: '通知收件人',
    description: '多个用逗号分隔',
    secret: false,
    envKey: 'NOTIFY_EMAIL_TO',
    placeholder: 'ops@example.com',
  },
  {
    key: 'SMTP_HOST',
    group: 'notify',
    label: 'SMTP 服务器',
    description: '例如 smtp.qq.com / smtp.163.com / smtp.exmail.qq.com',
    secret: false,
    envKey: 'SMTP_HOST',
    placeholder: 'smtp.qq.com',
  },
  {
    key: 'SMTP_PORT',
    group: 'notify',
    label: 'SMTP 端口',
    description: 'SSL 通常 465，STARTTLS 通常 587',
    secret: false,
    envKey: 'SMTP_PORT',
    placeholder: '465',
  },
  {
    key: 'SMTP_SECURE',
    group: 'notify',
    label: 'SMTP 加密方式',
    description: '465 端口选 SSL；587 端口选 STARTTLS',
    secret: false,
    envKey: 'SMTP_SECURE',
    options: [
      { value: 'true', label: 'SSL（直连，通常 465）' },
      { value: 'false', label: 'STARTTLS（通常 587）' },
    ],
  },
  {
    key: 'SMTP_USER',
    group: 'notify',
    label: 'SMTP 账号',
    description: '通常是完整邮箱地址',
    secret: false,
    envKey: 'SMTP_USER',
  },
  {
    key: 'SMTP_PASSWORD',
    group: 'notify',
    label: 'SMTP 密码/授权码',
    description: '加密存储；QQ/163 邮箱需要填"授权码"而不是登录密码',
    secret: true,
    envKey: 'SMTP_PASSWORD',
  },
  {
    key: 'SMTP_FROM',
    group: 'notify',
    label: '发件人显示名',
    description: '留空则用 SMTP 账号',
    secret: false,
    envKey: 'SMTP_FROM',
    placeholder: 'MediaFlow 运营助手',
  },
  {
    key: 'NOTIFY_ON_PUBLISH_FAILURE',
    group: 'notify',
    label: '发布失败时通知',
    description: '默认开启：任务彻底失败（超过重试次数）时推送',
    secret: false,
    envKey: 'NOTIFY_ON_PUBLISH_FAILURE',
    options: [
      { value: 'true', label: '开启' },
      { value: 'false', label: '关闭' },
    ],
  },
  {
    key: 'ACCOUNT_EXPIRY_WARN_DAYS',
    group: 'notify',
    label: '账号授权到期提前提醒天数',
    description: '默认 7 天；到期或刷新失败会推送提醒（同一账号每天最多提醒一次）',
    secret: false,
    envKey: 'ACCOUNT_EXPIRY_WARN_DAYS',
    placeholder: '7',
  },
  {
    key: 'MEDIA_STORAGE_DIR',
    group: 'media',
    label: '素材存放目录',
    description: '相对仓库根或绝对路径；换服务器时可指到数据盘/对象存储挂载点',
    secret: false,
    envKey: 'MEDIA_STORAGE_DIR',
    placeholder: 'uploads/media',
  },
  {
    key: 'MEDIA_TMP_DIR',
    group: 'media',
    label: '上传临时目录',
    description: '留空使用系统临时目录下的 mediaflow-upload（自动 0700）；可指到独立磁盘',
    secret: false,
    envKey: 'MEDIA_TMP_DIR',
    placeholder: '/data/mediaflow-tmp',
  },
  {
    key: 'MEDIA_MAX_CONCURRENT_UPLOADS',
    group: 'media',
    label: '同一用户的上传并发上限',
    description: '默认 3；0 表示不限。超限返回 429，计数 TTL 60 秒',
    secret: false,
    envKey: 'MEDIA_MAX_CONCURRENT_UPLOADS',
    placeholder: '3',
  },
  {
    key: 'MEDIA_UPLOAD_TTL_SECONDS',
    group: 'media',
    label: '上传并发计数 TTL（秒）',
    description: '默认 60；即使进程被强杀，计数也会自动过期，不会永久锁死用户',
    secret: false,
    envKey: 'MEDIA_UPLOAD_TTL_SECONDS',
    placeholder: '60',
  },
  {
    key: 'MEDIA_MAX_FILE_MB',
    group: 'media',
    label: '单个文件大小上限（MB）',
    description: '默认 50',
    secret: false,
    envKey: 'MEDIA_MAX_FILE_MB',
    placeholder: '50',
  },
  {
    key: 'MEDIA_ALLOWED_TYPES',
    group: 'media',
    label: '允许的文件类型（MIME，逗号分隔）',
    description: '默认图片 jpeg/png/webp/gif、视频 mp4/quicktime/webm、音频 mpeg/wav',
    secret: false,
    envKey: 'MEDIA_ALLOWED_TYPES',
    placeholder: 'image/jpeg,image/png,image/webp,video/mp4',
  },
  {
    key: 'MEDIA_PUBLIC_BASE_URL',
    group: 'media',
    label: '素材访问前缀',
    description: '留空用 /api/public/media/；也可填 CDN/对象存储域名，例如 https://cdn.example.com/media',
    secret: false,
    envKey: 'MEDIA_PUBLIC_BASE_URL',
  },
  {
    key: 'MEDIA_PUBLIC_RATE_LIMIT_PER_MINUTE',
    group: 'media',
    label: '素材公开访问限流（次/分钟/IP）',
    description: '公开素材接口无需登录即可访问，按来源 IP 限流防刷；0 表示不限制，默认 120',
    secret: false,
    envKey: 'MEDIA_PUBLIC_RATE_LIMIT_PER_MINUTE',
    placeholder: '120',
  },
  {
    key: 'AI_SYSTEM_PROMPT',
    group: 'ai',
    label: 'AI 写作规范（系统提示词）',
    description: '全局写作基调与合规要求；换行业主要改这里',
    secret: false,
    envKey: 'AI_SYSTEM_PROMPT',
  },
  {
    key: 'AI_PLATFORM_GUIDANCE',
    group: 'ai',
    label: '各平台风格指引（JSON）',
    description: 'key 为平台代码，value 为该平台的写作要求',
    secret: false,
    envKey: 'AI_PLATFORM_GUIDANCE',
    placeholder: '{"xiaohongshu":"种草笔记，第一人称，300 字以内"}',
  },
  {
    key: 'AI_TEMPERATURE',
    group: 'ai',
    label: '生成随机度（temperature）',
    description: '0-2，越大越发散；合规要求高的场景建议 0.3-0.7',
    secret: false,
    envKey: 'AI_TEMPERATURE',
    placeholder: '0.7',
  },
  {
    key: 'AI_MAX_TOKENS',
    group: 'ai',
    label: '最大输出长度（token）',
    description: '推理模型的思考过程也占这个额度，给少了会只有思考没有正文',
    secret: false,
    envKey: 'AI_MAX_TOKENS',
    placeholder: '4096',
  },
  {
    key: 'AI_JSON_MAX_TOKENS',
    group: 'ai',
    label: 'JSON 任务最大输出长度（token）',
    description: '生成结构化结果（多平台改写、资料草稿）用；推理模型的思考也占这个额度，给少了 JSON 会被截断',
    secret: false,
    envKey: 'AI_JSON_MAX_TOKENS',
    placeholder: '8192',
  },
  {
    key: 'AI_USD_CNY_RATE',
    group: 'ai',
    label: '美元兑人民币汇率',
    description: '模型官方价是美元，按这个汇率折算成人民币展示（默认 7）',
    secret: false,
    envKey: 'AI_USD_CNY_RATE',
    placeholder: '7',
  },
  {
    key: 'AI_PROVIDER_CONFIGS',
    group: 'ai',
    label: '多供应商配置',
    description: '多供应商（DeepSeek / GPT / Claude / GLM …）的密钥、地址与模型清单；建议在「AI 用量」界面里维护，密钥加密存储',
    secret: true,
    envKey: 'AI_PROVIDER_CONFIGS',
  },
  {
    key: 'AI_MODEL_PRICES',
    group: 'ai',
    label: '模型价格覆盖（JSON）',
    description: '官方价调整时可覆盖单个模型：{"openai/gpt-5.5":{"input":9,"output":72,"cacheRead":0.9}}，单位元/百万 token',
    secret: false,
    envKey: 'AI_MODEL_PRICES',
    placeholder: '{"deepseek/deepseek-flash":{"input":2,"output":3,"cacheRead":0.2}}',
  },
  {
    key: 'AI_PRICE_INPUT_PER_MTOK',
    group: 'ai',
    label: '输入价格（元/百万 token）',
    description: '用于统计 AI 花费；按服务商当前价格填写，填 0 表示不计成本',
    secret: false,
    envKey: 'AI_PRICE_INPUT_PER_MTOK',
    placeholder: '2',
  },
  {
    key: 'AI_PRICE_CACHED_INPUT_PER_MTOK',
    group: 'ai',
    label: '输入价格·缓存命中（元/百万 token）',
    description: '大模型对命中提示词缓存的输入单独计价（通常是未命中价的 1/4）；留空则按未命中价计算',
    secret: false,
    envKey: 'AI_PRICE_CACHED_INPUT_PER_MTOK',
    placeholder: '0.5',
  },
  {
    key: 'AI_PRICE_OUTPUT_PER_MTOK',
    group: 'ai',
    label: '输出价格（元/百万 token）',
    description: '用于统计 AI 花费；推理模型的思考 token 也算输出',
    secret: false,
    envKey: 'AI_PRICE_OUTPUT_PER_MTOK',
    placeholder: '8',
  },
  {
    key: 'AI_RATE_LIMIT_PER_MINUTE',
    group: 'ai',
    label: '每分钟最多生成次数',
    description: '防止误触发把额度刷掉；填 0 表示不限制',
    secret: false,
    envKey: 'AI_RATE_LIMIT_PER_MINUTE',
    placeholder: '0',
  },
  {
    key: 'AI_DAILY_TOKEN_QUOTA',
    group: 'ai',
    label: '每日 token 上限',
    description: '当天累计 token 达到上限后停止调用，避免账单失控；填 0 表示不限制',
    secret: false,
    envKey: 'AI_DAILY_TOKEN_QUOTA',
    placeholder: '0',
  },
  {
    key: 'COMPLIANCE_RULES',
    group: 'compliance',
    label: '合规词库（JSON）',
    description: '违规词、原因与修改建议；换行业/换品类时按自己的红线改一遍即可',
    secret: false,
    envKey: 'COMPLIANCE_RULES',
  },
  {
    key: 'KB_INJECT_LIMIT',
    group: 'knowledge',
    label: 'AI 每次引用的资料条数',
    description: '默认 5 条，太多会稀释重点并推高 token 消耗',
    secret: false,
    envKey: 'KB_INJECT_LIMIT',
    placeholder: '5',
  },
  {
    key: 'KB_CHUNK_SIZE',
    group: 'knowledge',
    label: '文档切片长度（字）',
    description: '默认 1200',
    secret: false,
    envKey: 'KB_CHUNK_SIZE',
    placeholder: '1200',
  },
  {
    key: 'KB_CHUNK_OVERLAP',
    group: 'knowledge',
    label: '切片重叠长度（字）',
    description: '默认 200，避免语义被切断',
    secret: false,
    envKey: 'KB_CHUNK_OVERLAP',
    placeholder: '200',
  },
  {
    key: 'KB_MAX_CHUNKS',
    group: 'knowledge',
    label: '单份文档最多切片数',
    description: '默认 40，防止一份大文档灌爆知识库',
    secret: false,
    envKey: 'KB_MAX_CHUNKS',
    placeholder: '40',
  },
  {
    key: 'KB_MAX_DOCUMENT_MB',
    group: 'knowledge',
    label: '单文件大小上限（MB）',
    description: '默认 10',
    secret: false,
    envKey: 'KB_MAX_DOCUMENT_MB',
    placeholder: '10',
  },
  {
    key: 'KB_OCR_ENABLED',
    group: 'knowledge',
    label: '启用本地图片文字识别（OCR）',
    description: '离线 tesseract，不调用任何 AI 接口',
    secret: false,
    envKey: 'KB_OCR_ENABLED',
    options: [
      { value: 'true', label: '启用' },
      { value: 'false', label: '停用' },
    ],
  },
  {
    key: 'KB_OCR_LANGUAGES',
    group: 'knowledge',
    label: 'OCR 语言包',
    description: 'tesseract 语言代码，默认 chi_sim+eng',
    secret: false,
    envKey: 'KB_OCR_LANGUAGES',
    placeholder: 'chi_sim+eng',
  },
  {
    key: 'KB_OCR_MAX_IMAGES',
    group: 'knowledge',
    label: '单文档最多识别图片数',
    description: '默认 20',
    secret: false,
    envKey: 'KB_OCR_MAX_IMAGES',
    placeholder: '20',
  },
  {
    key: 'KB_OCR_PDF_MAX_PAGES',
    group: 'knowledge',
    label: '扫描版 PDF 最多识别页数',
    description: '默认 10',
    secret: false,
    envKey: 'KB_OCR_PDF_MAX_PAGES',
    placeholder: '10',
  },
  {
    key: 'KB_OCR_DPI',
    group: 'knowledge',
    label: 'PDF 渲染精度（DPI）',
    description: '默认 200，越大越准但越慢',
    secret: false,
    envKey: 'KB_OCR_DPI',
    placeholder: '200',
  },
  {
    key: 'NOTIFICATION_RETENTION_DAYS',
    group: 'publish',
    label: '通知保留天数',
    description: '超过该天数的站内通知会被自动清理（默认 90，填 0 表示永久保留）',
    secret: false,
    envKey: 'NOTIFICATION_RETENTION_DAYS',
    placeholder: '90',
  },
  {
    key: 'AI_METADATA_ENABLED',
    group: 'publish',
    label: '发布时写入 AI 生成标识元数据',
    description: '按《人工智能生成合成内容标识办法》要求，AI 生成内容的图片/视频需要隐式标识；开启后发布负载会带上元数据',
    secret: false,
    envKey: 'AI_METADATA_ENABLED',
    options: [
      { value: 'true', label: '开启' },
      { value: 'false', label: '关闭' },
    ],
  },
  {
    key: 'PUBLISH_STREAM_NAME',
    group: 'publish',
    label: '队列名称',
    description: 'Redis Stream 名称，默认 mediaflow:publish:tasks；改名前请确认没有排队中的任务',
    secret: false,
    envKey: 'PUBLISH_STREAM_NAME',
    placeholder: 'mediaflow:publish:tasks',
  },
  {
    key: 'PUBLISH_GROUP_NAME',
    group: 'publish',
    label: '消费组名称',
    description: '默认 publish-workers；与队列名一起改可让新环境使用独立队列',
    secret: false,
    envKey: 'PUBLISH_GROUP_NAME',
    placeholder: 'publish-workers',
  },
  {
    key: 'PUBLISH_STREAM_MAXLEN',
    group: 'publish',
    label: '队列最大长度（条）',
    description: 'Redis Stream 近似修剪上限（MAXLEN ~）。已消费的旧消息会被丢弃，未确认的任务不受影响；默认 10000',
    secret: false,
    envKey: 'PUBLISH_STREAM_MAXLEN',
    placeholder: '10000',
  },
  {
    key: 'PUBLISH_STUCK_MINUTES',
    group: 'publish',
    label: '任务卡住判定（分钟）',
    description: '任务被 worker 领取后超过这个时间仍未结束，就在「队列运维」里标为卡住并可强制重排（默认 15）',
    secret: false,
    envKey: 'PUBLISH_STUCK_MINUTES',
    placeholder: '15',
  },
  {
    key: 'PUBLISH_MAX_ATTEMPTS',
    group: 'publish',
    label: '失败最多重试次数',
    description: '默认 3',
    secret: false,
    envKey: 'PUBLISH_MAX_ATTEMPTS',
    placeholder: '3',
  },
  {
    key: 'PUBLISH_READ_BLOCK_MS',
    group: 'publish',
    label: '队列空闲轮询间隔（毫秒）',
    description: '默认 5000',
    secret: false,
    envKey: 'PUBLISH_READ_BLOCK_MS',
    placeholder: '5000',
  },
  {
    key: 'PUBLISH_READ_COUNT',
    group: 'publish',
    label: '每次领取任务数',
    description: '默认 5',
    secret: false,
    envKey: 'PUBLISH_READ_COUNT',
    placeholder: '5',
  },
  {
    key: 'PUBLISH_CLAIM_IDLE_MS',
    group: 'publish',
    label: '卡住任务回收阈值（毫秒）',
    description: '默认 60000，worker 中途挂掉后超过这个时间会被重新领取',
    secret: false,
    envKey: 'PUBLISH_CLAIM_IDLE_MS',
    placeholder: '60000',
  },
  {
    key: 'KB_CATEGORIES',
    group: 'knowledge',
    label: '知识库分类配置',
    description: 'JSON 数组。平时不用手改——在「知识库管理 → 分类设置」里增删改即可，这里显示当前值，也方便整包配置导入导出',
    secret: false,
    envKey: 'KB_CATEGORIES',
    placeholder: '[{"code":"product","label":"产品卖点","tone":"success","description":"配方、规格、工艺"}]',
  },
  {
    key: 'WECHAT_MP_APP_ID',
    group: 'platform',
    label: '公众号 AppID',
    description: '用于拉取图文分析数据；公众号禁止 API 发布，仅供人工发布',
    secret: false,
    envKey: 'WECHAT_MP_APP_ID',
  },
  {
    key: 'WECHAT_MP_APP_SECRET',
    group: 'platform',
    label: '公众号 AppSecret',
    description: '加密存储',
    secret: true,
    envKey: 'WECHAT_MP_APP_SECRET',
  },
  {
    key: 'DOUYIN_CLIENT_KEY',
    group: 'platform',
    label: '抖音 Client Key',
    description: '发布接口需要 OAuth 授权；互动接口不可用',
    secret: false,
    envKey: 'DOUYIN_CLIENT_KEY',
  },
  {
    key: 'DOUYIN_CLIENT_SECRET',
    group: 'platform',
    label: '抖音 Client Secret',
    description: '加密存储',
    secret: true,
    envKey: 'DOUYIN_CLIENT_SECRET',
  },
  {
    key: 'XIAOHONGSHU_APP_ID',
    group: 'platform',
    label: '小红书 App ID',
    description: '需企业资质认证',
    secret: false,
    envKey: 'XIAOHONGSHU_APP_ID',
  },
  {
    key: 'XIAOHONGSHU_APP_SECRET',
    group: 'platform',
    label: '小红书 App Secret',
    description: '加密存储',
    secret: true,
    envKey: 'XIAOHONGSHU_APP_SECRET',
  },
  {
    key: 'XIAOHONGSHU_API_BASE',
    group: 'platform',
    label: '小红书开放平台地址',
    description: '留空时适配器不发起请求，只返回明确报错',
    secret: false,
    envKey: 'XIAOHONGSHU_API_BASE',
  },
  {
    key: 'BAIJIAHAO_APP_ID',
    group: 'platform',
    label: '百家号 app_id',
    description: '百家号后台开通「开发者服务」后获取（作者帐号ID）',
    secret: false,
    envKey: 'BAIJIAHAO_APP_ID',
  },
  {
    key: 'BAIJIAHAO_APP_TOKEN',
    group: 'platform',
    label: '百家号 app_token',
    description: '开发者服务授权密钥，加密存储，长期有效',
    secret: true,
    envKey: 'BAIJIAHAO_APP_TOKEN',
  },
  {
    key: 'REQUIRE_CONTENT_APPROVAL',
    group: 'publish',
    label: '发布前必须审核通过',
    description: '开启后，只有审核状态为「已通过」的内容才能创建发布任务',
    secret: false,
    envKey: 'REQUIRE_CONTENT_APPROVAL',
    options: [
      { value: 'true', label: '开启（推荐多人协作）' },
      { value: 'false', label: '关闭（小团队直接发布）' },
    ],
  },
  {
    key: 'PUBLISH_WORKER_ENABLED',
    group: 'publish',
    label: '启用发布 Worker',
    description: '关闭后任务只入队不执行（修改后需重启 API 生效）',
    secret: false,
    envKey: 'PUBLISH_WORKER_ENABLED',
    options: [
      { value: 'true', label: '启用' },
      { value: 'false', label: '停用' },
    ],
  },
  {
    key: 'PUBLISH_RETRY_INTERVAL_MS',
    group: 'publish',
    label: '失败重试间隔（毫秒）',
    description: '默认 300000（5 分钟）',
    secret: false,
    envKey: 'PUBLISH_RETRY_INTERVAL_MS',
    placeholder: '300000',
  },
  {
    key: 'WORKSPACE_SOFT_DELETE_RETENTION_DAYS',
    group: 'workspace',
    label: '工作区删除保留天数',
    description: '工作区删除后进入保留期，期间可恢复；到期后由定时任务永久清除。默认 30 天，可设 7-365 天（对外合同时按约定调整）',
    secret: false,
    envKey: 'WORKSPACE_SOFT_DELETE_RETENTION_DAYS',
    placeholder: '30',
  },
  {
    key: 'WORKSPACE_PURGE_BACKUP_RETENTION_DAYS',
    group: 'workspace',
    label: '永久清除前备份保留天数',
    description: '永久清除前会自动导出该工作区数据到独立备份文件（清除的唯一后悔药）；默认 180 天，到期由清理任务删除并写审计',
    secret: false,
    envKey: 'WORKSPACE_PURGE_BACKUP_RETENTION_DAYS',
    placeholder: '180',
  },
  {
    key: 'MONITOR_ENABLED',
    group: 'monitor',
    label: '开启运行监控',
    description: '定时巡检队列堆积、卡住任务、发布失败率、登录失败激增、上传磁盘用量与 AI 配额，命中阈值即告警',
    secret: false,
    envKey: 'MONITOR_ENABLED',
    options: [
      { value: 'true', label: '开启' },
      { value: 'false', label: '关闭' },
    ],
  },
  {
    key: 'MONITOR_INTERVAL_SECONDS',
    group: 'monitor',
    label: '巡检间隔（秒）',
    description: '默认 300（5 分钟）；实际执行由每分钟的定时器按该间隔触发',
    secret: false,
    envKey: 'MONITOR_INTERVAL_SECONDS',
    placeholder: '300',
  },
  {
    key: 'MONITOR_QUEUE_LENGTH_THRESHOLD',
    group: 'monitor',
    label: '队列长度告警阈值（条）',
    description: '发布队列积压超过该条数即告警，默认 100',
    secret: false,
    envKey: 'MONITOR_QUEUE_LENGTH_THRESHOLD',
    placeholder: '100',
  },
  {
    key: 'MONITOR_PENDING_AGE_SECONDS',
    group: 'monitor',
    label: '未确认消息超时（秒）',
    description: '存在超过该时长仍未被确认（未 ack）的消息即告警，默认 300（5 分钟）',
    secret: false,
    envKey: 'MONITOR_PENDING_AGE_SECONDS',
    placeholder: '300',
  },
  {
    key: 'MONITOR_FAILURE_RATE_PERCENT',
    group: 'monitor',
    label: '发布失败率告警阈值（%）',
    description: '近 1 小时发布任务的失败占比超过该值即告警，默认 10',
    secret: false,
    envKey: 'MONITOR_FAILURE_RATE_PERCENT',
    placeholder: '10',
  },
  {
    key: 'MONITOR_FAILURE_MIN_SAMPLE',
    group: 'monitor',
    label: '失败率最小样本量（条）',
    description: '近 1 小时任务数少于该值时不做失败率告警，避免样本太少误报，默认 5',
    secret: false,
    envKey: 'MONITOR_FAILURE_MIN_SAMPLE',
    placeholder: '5',
  },
  {
    key: 'MONITOR_LOGIN_FAIL_THRESHOLD',
    group: 'monitor',
    label: '登录失败次数告警阈值（次）',
    description: '窗口期内登录失败次数超过该值即告警，默认 20',
    secret: false,
    envKey: 'MONITOR_LOGIN_FAIL_THRESHOLD',
    placeholder: '20',
  },
  {
    key: 'MONITOR_LOGIN_FAIL_WINDOW_MINUTES',
    group: 'monitor',
    label: '登录失败统计窗口（分钟）',
    description: '登录失败计数的滚动窗口长度，默认 5',
    secret: false,
    envKey: 'MONITOR_LOGIN_FAIL_WINDOW_MINUTES',
    placeholder: '5',
  },
  {
    key: 'MONITOR_DISK_USED_PERCENT',
    group: 'monitor',
    label: '上传磁盘使用率告警阈值（%）',
    description: '素材存储所在磁盘使用率超过该值即告警，默认 80',
    secret: false,
    envKey: 'MONITOR_DISK_USED_PERCENT',
    placeholder: '80',
  },
  {
    key: 'MONITOR_AI_QUOTA_PERCENT',
    group: 'monitor',
    label: 'AI 日配额告警阈值（%）',
    description: '当日 token 消耗达到 AI 日配额的该比例即告警，默认 80；未配置配额时跳过',
    secret: false,
    envKey: 'MONITOR_AI_QUOTA_PERCENT',
    placeholder: '80',
  },
  {
    key: 'MONITOR_ALERT_COOLDOWN_MINUTES',
    group: 'monitor',
    label: '同类告警冷却（分钟）',
    description: '同一种告警在该时长内只发一次，避免刷屏，默认 30',
    secret: false,
    envKey: 'MONITOR_ALERT_COOLDOWN_MINUTES',
    placeholder: '30',
  },
  {
    key: 'MONITOR_OPS_BASE_URL',
    group: 'monitor',
    label: '排查链接前缀',
    description: '告警文案里的排查链接前缀，默认 https://auto.liangyijianye.cn',
    secret: false,
    envKey: 'MONITOR_OPS_BASE_URL',
    placeholder: 'https://auto.liangyijianye.cn',
  },
];


export const SETTING_BY_KEY = new Map(SETTING_DEFINITIONS.map((definition) => [definition.key, definition]));

export const SETTING_GROUP_LABELS: Record<SettingGroup, string> = {
  site: '站点信息',
  permissions: '角色与权限',
  media: '素材库',
  notify: '通知渠道',
  ai: 'AI 服务',
  compliance: '合规词库',
  knowledge: '知识库',
  publish: '发布队列',
  platform: '平台密钥',
  monitor: '运行监控',
  workspace: '工作区与租户',
};
